name: Release Build

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Attach Release Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, macos]
        arch: [amd64, arm64, arm]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.7

    - name: Build binary
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ./bin/commit-wizard-${{ matrix.os }}-${{ matrix.arch }} cmd/commit-wizard/main.go

    - name: Upload binary to release
      uses: softprops/action-gh-release@v1
      with:
        files: ./bin/commit-wizard-${{ matrix.os }}-${{ matrix.arch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
